language: python
sudo: false
python:
- 2.7
- 3.5
addons:
  apt:
    packages:
    - libzmq3-dev

install:
- python setup.py install
- pip install -e .[test]
- pip install coveralls

script:
- python setup.py nosetests
- coverage report -m

after_success:
- coveralls

notifications:
  slack:
    secure: k5inOHwm0US/aBrjhpgYWGrfOBJgzlm2VkIJ5719gwiyECn/Zap2VVrPxqZVg1xCMPHHIiQMxweMKJseRx0vsdYITXRWwo2VooENQgwdwL9yKgpWl11teCueDN5575qqEqI+j5VwNDdDG425KuvTwF3Y3PVMrlPKataOYkkXnPZfozYtIRo4OOB4rNBH0AOHnGdp3D1tfggqRL9fByV2YLi0zWaA6e1BTDnXXtdj0qHjMMlaVU6H6vrz1nmiq/IrwnPTakomIt89aFh9uYBwkpDkg2ry/rxnd91RuSQweN/27A5Hr+zXN4HdwJNOLuacuaAk6yqO41XCZzvgKhQCTNkv8rzzYZHofJrbXN67TMiR7vvcT5Wv+CT0QVvtD7XBFDJkofZYKcPMxqB4ALB6pJOB1YdD8revqH+u3LTgfxCgKXaZTkOr8LAYvsVDU5OjFGS2AY6+O5uJaR43c1VPtCCh8JBigMKlzN4IM1ZeGqbear8zlOlFvp5L7lua+aI3Jlg/oo24wFuebt0d+tVC2qf5HM6NT473xj1kfoy7IY18Dfr1IX3B/EUVhBSjKDMp1YvGoUg2sNYLS/tqW+J9ObYqgqtFPqe9IUp9e2fNox8I+dpRyoxVrWMfX1G+LiS4dZzn1fogotOYUzwUX4A/Se5oBmRvax3lnKI8BY44ybk=
