dist: xenial
language: python
sudo: false
python:
- 2.7
- 3.7
addons:
  apt:
    packages:
    - libzmq3-dev
  code_climate:
    repo_token: ef76afe3f9ae2674684b27eb61c9a08b08bf887a85a1f304a08c93ff12b9b3f7

install:
- pip install -e .
- pip install -e .[test]
- pip install coveralls
- pip install codeclimate-test-reporter

script:
- python setup.py nosetests
- coverage report -m

after_success:
- coveralls
- CODECLIMATE_REPO_TOKEN=ef76afe3f9ae2674684b27eb61c9a08b08bf887a85a1f304a08c93ff12b9b3f7 codeclimate-test-reporter

notifications:
  slack:
    secure: k5inOHwm0US/aBrjhpgYWGrfOBJgzlm2VkIJ5719gwiyECn/Zap2VVrPxqZVg1xCMPHHIiQMxweMKJseRx0vsdYITXRWwo2VooENQgwdwL9yKgpWl11teCueDN5575qqEqI+j5VwNDdDG425KuvTwF3Y3PVMrlPKataOYkkXnPZfozYtIRo4OOB4rNBH0AOHnGdp3D1tfggqRL9fByV2YLi0zWaA6e1BTDnXXtdj0qHjMMlaVU6H6vrz1nmiq/IrwnPTakomIt89aFh9uYBwkpDkg2ry/rxnd91RuSQweN/27A5Hr+zXN4HdwJNOLuacuaAk6yqO41XCZzvgKhQCTNkv8rzzYZHofJrbXN67TMiR7vvcT5Wv+CT0QVvtD7XBFDJkofZYKcPMxqB4ALB6pJOB1YdD8revqH+u3LTgfxCgKXaZTkOr8LAYvsVDU5OjFGS2AY6+O5uJaR43c1VPtCCh8JBigMKlzN4IM1ZeGqbear8zlOlFvp5L7lua+aI3Jlg/oo24wFuebt0d+tVC2qf5HM6NT473xj1kfoy7IY18Dfr1IX3B/EUVhBSjKDMp1YvGoUg2sNYLS/tqW+J9ObYqgqtFPqe9IUp9e2fNox8I+dpRyoxVrWMfX1G+LiS4dZzn1fogotOYUzwUX4A/Se5oBmRvax3lnKI8BY44ybk=
